apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $K8S_APPLICATION
    service: shopping
    shard: blue
  name: shopping-blue
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $K8S_APPLICATION
      service: shopping
      shard: blue
  template:
    metadata:
      labels:
        app: $K8S_APPLICATION
        service: shopping
        shard: blue
    spec:
      containers:
      - name: shopping
        image: ${K8S_REPOSITORY}shopping:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-jar"
        - "/shopping.jar"
        - "server"
        - "/conf/shopping-app.yaml"
        ports:
        - containerPort: 50050
          name: application
          protocol: TCP
        - containerPort: 50150
          name: admin
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $K8S_APPLICATION
    service: shopping
    shard: green
  name: shopping-green
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $K8S_APPLICATION
      service: shopping
      shard: green
  template:
    metadata:
      labels:
        app: $K8S_APPLICATION
        service: shopping
        shard: green
    spec:
      containers:
        - name: shopping
          image: ${K8S_REPOSITORY}shopping:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/shopping.jar"
            - "server"
            - "/conf/shopping-app.yaml"
          ports:
            - containerPort: 50050
              name: application
              protocol: TCP
            - containerPort: 50150
              name: admin
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744

