apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $K8S_APPLICATION
    service: packaging
    shard: blue
  name: packaging-blue
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $K8S_APPLICATION
      service: packaging
      shard: blue
  template:
    metadata:
      labels:
        app: $K8S_APPLICATION
        service: packaging
        shard: blue
    spec:
      containers:
      - name: packaging
        image: ${K8S_REPOSITORY}packaging:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-jar"
        - "/packaging.jar"
        - "/conf/packaging-app.yaml"
        ports:
        - containerPort: 50053
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $K8S_APPLICATION
    service: packaging
    shard: green
  name: packaging-green
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $K8S_APPLICATION
      service: packaging
      shard: green
  template:
    metadata:
      labels:
        app: $K8S_APPLICATION
        service: packaging
        shard: green
    spec:
      containers:
        - name: packaging
          image: ${K8S_REPOSITORY}packaging:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/packaging.jar"
            - "/conf/packaging-app.yaml"
          ports:
            - containerPort: 50053
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: packaging
  namespace: $K8S_NAMESPACE
spec: 
  selector:
    app: $K8S_APPLICATION
    service: packaging
  type: ClusterIP
  ports:
  - name: application
    port: 50053

