apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $K8S_APPLICATION
    service: notification
    shard: blue
  name: notification-blue
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $K8S_APPLICATION
      service: notification
      shard: blue
  template:
    metadata:
      labels:
        app: $K8S_APPLICATION
        service: notification
        shard: blue
    spec:
      containers:
      - name: notification
        image: ${K8S_REPOSITORY}notification:latest
        imagePullPolicy: Always 
        command:
        - "java"
        - "-jar"
        - "/notification.jar"
        - "--spring.config.location=/conf/notification-app.yaml"
        ports:
        - containerPort: 50056
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $K8S_APPLICATION
    service: notification
    shard: green
  name: notification-green
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $K8S_APPLICATION
      service: notification
      shard: green
  template:
    metadata:
      labels:
        app: $K8S_APPLICATION
        service: notification
        shard: green
    spec:
      containers:
        - name: notification
          image: ${K8S_REPOSITORY}notification:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/notification.jar"
            - "--spring.config.location=/conf/notification-app.yaml"
          ports:
            - containerPort: 50056
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: $K8S_NAMESPACE
spec: 
  selector:
    app: $K8S_APPLICATION
    service: notification  
  type: ClusterIP
  ports:
  - name: application
    port: 50056

